/* This file is generated by scm2c */

/* File head */

#include <config.h>

#include <svm.h>
#include <scheme.h>
#include <gc.h>
#include <builtin.h>

#include <debug.h>

#include <stdio.h>
#include <stdlib.h>

static void _Func_scm_iter_0();
SCHEME_DECL(Closure, _Closure_scm_iter_1);
SCHEME_DECL(Symbol, _Symbol_scm_3);
SCHEME_DECL(Symbol, _Symbol_scm_5);
SCHEME_DECL(Pair, _Pair_scm_6);
SCHEME_DECL(Pair, _Pair_scm_7);

static SCHEME_DEF_TEMPLATE(_iter_scm_0, _Func_scm_iter_0);
SCHEME_DEF_CONST(Closure, _Closure_scm_iter_1, NULL, _iter_scm_0);
static char _c_string_scm_2[] = "a";
SCHEME_DEF_CONST(Symbol, _Symbol_scm_3, _c_string_scm_2, 1);
static char _c_string_scm_4[] = "b";
SCHEME_DEF_CONST(Symbol, _Symbol_scm_5, _c_string_scm_4, 1);
SCHEME_DEF_CONST(Pair, _Pair_scm_6, (SCHEME_CTYPE(Obj) *) _Symbol_scm_5,
                 (SCHEME_CTYPE(Obj) *) scheme_null);
SCHEME_DEF_CONST(Pair, _Pair_scm_7, (SCHEME_CTYPE(Obj) *) _Symbol_scm_3,
                 (SCHEME_CTYPE(Obj) *) _Pair_scm_6);

static void _c_Func_scm_iter_0()
{
    BEGIN_PROC(_Func_scm_iter_0);

    NEW_ENVT(1);
    EXTEND_ENVT(svm_register(new));
    ACCESS_STACK(0);
    BIND_VAR(g_svm.reg_envt, 0);
    LOOKUP_VAR(g_svm.reg_envt, 0);
    svm_push();

    M_builtin_car(1);
    MOVESP(1);

    svm_push();

    M_builtin_display(1);
    MOVESP(1);

    LOOKUP_VAR(g_svm.reg_envt, 0);
    svm_push();

    M_builtin_null_p(1);
    MOVESP(1);

    if (SCHEME_TRUEP(svm_register(value))) {
        svm_register(value) = (SCHEME_CTYPE(Obj) *) scheme_true;
    } else {
        LOOKUP_VAR(g_svm.reg_envt, 0);
        svm_push();

        M_builtin_cdr(1);
        MOVESP(1);

        svm_push();

        LOOKUP_VAR(g_svm.reg_envt->enclosing, 0);
        apply_procedure();

    }
    LEAVE_PROC();
}


void mod_init()
{
    SCHEME_ENVT_BINDINGS(global_environment) = alloc_binds(1);
}

static void iter_mod_run()
{
    push_continuation(scheme_return);

    SCHEME_CLOSURE_ENVT(_Closure_scm_iter_1) = g_svm.reg_envt;
    svm_register(value) = (Scheme_Obj_t *) _Closure_scm_iter_1;

    BIND_VAR(g_svm.reg_envt, 0);

    push_continuation(.L_scm_4);
    svm_register(value) = (SCHEME_CTYPE(Obj) *) _Pair_scm_7;
    svm_push();

    LOOKUP_VAR(g_svm.reg_envt, 0);
    apply_procedure();
    LABEL(.L_scm_4);

    M_builtin_display(0);
    MOVESP(0);

    LABEL(scheme_return);
}


int main(int argc, char *argv[])
{
    scheme_init_all(STACK_SIZE);

    iter_mod_run();
    printf("Finish\n");

    return 0;
}
