/* This file is generated by scm2c */

/* File head */

#include <config.h>

#include <svm.h>
#include <scheme.h>
#include <gc.h>
#include <builtin.h>

#include <debug.h>

#include <stdio.h>
#include <stdlib.h>




void mod_init()
{
    SCHEME_ENVT_BINDINGS(global_environment) = alloc_binds(0);
}

static void psvmst_mod_run()
{
    push_continuation(scheme_return);

    M_builtin_psvmst(0);
    MOVESP(0);

    LABEL(scheme_return);
}


int main(int argc, char *argv[])
{
    scheme_init_all(STACK_SIZE);

    psvmst_mod_run();
    printf("Finish\n");

    return 0;
}
