/* This file is generated by scm2c */

/* File head */

#include <config.h>

#include <svm.h>
#include <scheme.h>
#include <gc.h>
#include <builtin.h>

#include <debug.h>

#include <stdio.h>
#include <stdlib.h>

static void _Func_scm_add_0();
SCHEME_DECL(Closure, _Closure_scm_add_1);

static SCHEME_DEF_TEMPLATE(_add_scm_0, _Func_scm_add_0);
SCHEME_DEF_CONST(Closure, _Closure_scm_add_1, NULL, _add_scm_0);

static void _c_Func_scm_add_0()
{
    BEGIN_PROC(_Func_scm_add_0);

    NEW_ENVT(3);
    EXTEND_ENVT(svm_register(new));
    ACCESS_STACK(0);
    BIND_VAR(g_svm.reg_envt, 0);
    ACCESS_STACK(1);
    BIND_VAR(g_svm.reg_envt, 1);
    ACCESS_STACK(2);
    BIND_VAR(g_svm.reg_envt, 2);
    LOOKUP_VAR(g_svm.reg_envt, 2);
    svm_push();

    LOOKUP_VAR(g_svm.reg_envt, 1);
    svm_push();

    LOOKUP_VAR(g_svm.reg_envt, 0);
    svm_push();

    M_builtin_add(3);
    MOVESP(3);

    LEAVE_PROC();
}


void mod_init()
{
    SCHEME_ENVT_BINDINGS(global_environment) = alloc_binds(1);
}

static void test_mod_run()
{
    push_continuation(scheme_return);

    SCHEME_CLOSURE_ENVT(_Closure_scm_add_1) = g_svm.reg_envt;
    svm_register(value) = (Scheme_Obj_t *) _Closure_scm_add_1;

    BIND_VAR(g_svm.reg_envt, 0);

    push_continuation(.L_scm_0);
    svm_register(value) = (SCHEME_CTYPE(Obj) *) SCHEME_INT_TO_OBJ(5);
    svm_push();

    svm_register(value) = (SCHEME_CTYPE(Obj) *) SCHEME_INT_TO_OBJ(4);
    svm_push();

    svm_register(value) = (SCHEME_CTYPE(Obj) *) SCHEME_INT_TO_OBJ(3);
    svm_push();

    LOOKUP_VAR(g_svm.reg_envt, 0);
    apply_procedure();
    LABEL(.L_scm_0);

    M_builtin_display(0);
    MOVESP(0);

    LABEL(scheme_return);
}


int main(int argc, char *argv[])
{
    scheme_init_all(STACK_SIZE);

    test_mod_run();
    printf("Finish\n");

    return 0;
}
