'(1 3 4 5 "fdf")
'(1 3 4 5 "fdf")
'(1 3 4 5 "fdf")
'(1 3 4 5 "fdf" FDf . f)
'()
(f 435)
(if (test 3)
    (add 4 6)
    (sub 6 2))
(lambda (a) 3)
(lambda a 5)
(lambda (a b c . d) (+ a b c d))
(define a 5)
(define (foo a b c) (+ a b c))
(define (foo a . b) b)
(define-syntax foo
  (syntax-rules () ((foo a) (+ 1 a))
                ))
(foo a)